name: BeardAch
main: me.tehbeard.BeardAch.BeardAch
version: ${project.plugin.version}
softdepend: [WorldGuard,DroxPerms,Vault,BeardStat] 
commands:
    ach:
        description: Show your achievements
        usage: /<command>
    ach-reload:
        description: reloads the achievements
        usage: /<command>
        permission: beardach.reload
    ach-fancy:
        description: dumps achievement definitions to database
        usage: /<command>
        permission: beardach.reload.fancy
    ach-admin:
        description: Administrative functions
        usage: /<command> dumpmeta|clearmeta
        permission: beardach.reload
permissions:
  beardach.reload:
    description: Allows you to reload the achievements list
    default: op
    children:
      beardach.reload.fancy: true
  beardach.reload.fancy:
    description: allows you to use /ach-fancy to make external ach displays
    default: false