name: BeardAch
main: com.tehbeard.beardach.BeardAch
version: ${project.plugin.version}
softdepend: [WorldGuard,DroxPerms,Vault,BeardStat] 
commands:
    ach:
        description: Show your achievements
        usage: /<command>
    ach-reload:
        description: reloads the achievements
        usage: /<command>
    ach-fancy:
        description: dumps achievement definitions to database
        usage: /<command>
    ach-admin:
        description: Administrative functions
        usage: /<command> dumpmeta|clearmeta
    ach-export:
        description: Exports the editor
        usage: /<command>
    testach:
        description: Test for achievement
        usage: /<command> playerSelector achievementId
permissions:
  beardach.reload:
    description: Allows you to reload the achievements list
    default: op
    children:
      beardach.reload.fancy: true
  beardach.reload.fancy:
    description: allows you to use /ach-fancy to make external ach displays
    default: false